// @generated by `bun run protocol:generate`
// Do not edit by hand. Rust protocol types in crates/nerve-runtime are the source of truth.

export const RUNTIME_DAEMON_NAME = "nerve" as const;
export const RUNTIME_EVENT_METHOD = "runtime/event" as const;
export const RUNTIME_INFO_METHOD = "runtime/info" as const;
export const RUNTIME_JOB_CANCEL_METHOD = "runtime/jobs/cancel" as const;
export const RUNTIME_JOB_GET_METHOD = "runtime/jobs/get" as const;
export const RUNTIME_JOB_LIST_METHOD = "runtime/jobs/list" as const;
export const RUNTIME_JOB_METHODS = ["runtime/jobs/start","runtime/jobs/get","runtime/jobs/list","runtime/jobs/cancel"] as const;
export const RUNTIME_JOB_START_METHOD = "runtime/jobs/start" as const;
export const RUNTIME_PROTOCOL_NAME = "nerve-runtime" as const;
export const RUNTIME_PROTOCOL_VERSION = "3" as const;
export const RUNTIME_TOOLS_LIST_METHOD = "runtime/tools/list" as const;

/**
 * Transport-neutral command understood by human-facing runtime adapters.
 */
export type RuntimeCommand =
  | {
      kind: "ping";
    }
  | {
      kind: "tool.list";
    }
  | {
      arguments?: {
        [k: string]: unknown;
      };
      kind: "tool.call";
      name: string;
    }
  | {
      kind: "agent.run";
      max_turns?: number | null;
      model: string;
      provider: string;
      reasoning_effort?: string | null;
      system_prompt?: string | null;
      task: string;
      temperature?: number | null;
      tool_filter?: string[] | null;
    }
  | {
      agent?: string | null;
      kind: "session.start";
      max_turns?: number | null;
      model: string;
      provider: string;
      reasoning_effort?: string | null;
      resume?: string | null;
      system_prompt?: string | null;
      temperature?: number | null;
      tool_filter?: string[] | null;
      workspace?: string | null;
    }
  | {
      kind: "session.message";
      session_id: string;
      text: string;
    }
  | {
      kind: "session.interrupt";
      session_id: string;
    }
  | {
      decision: SessionApprovalDecision;
      kind: "session.respond";
      request_id: string;
      session_id: string;
    }
  | {
      kind: "session.get";
      session_id: string;
    }
  | {
      kind: "session.list";
    }
  | {
      kind: "session.close";
      session_id: string;
    }
  | {
      kind: "session.set_model";
      model: string;
      provider?: string | null;
      session_id: string;
    }
  | {
      kind: "auth.start";
      provider: string;
    }
  | {
      callback_url?: string | null;
      code?: string | null;
      kind: "auth.complete";
      login_id: string;
    }
  | {
      kind: "auth.status";
      provider: string;
    }
  | {
      kind: "auth.logout";
      provider: string;
    };
/**
 * Decision supplied by a human/client for a session approval request.
 */
export type SessionApprovalDecision = "allow" | "deny";
/**
 * Runtime event emitted by human-facing adapters while executing jobs.
 */
export type RuntimeEvent =
  | {
      command: string;
      job_id: string;
      tool_name?: string | null;
      type: "job_started";
    }
  | {
      current?: number | null;
      job_id: string;
      message: string;
      stage: string;
      total?: number | null;
      type: "job_progress";
    }
  | {
      job_id: string;
      type: "job_cancel_requested";
    }
  | {
      job_id: string;
      type: "job_completed";
    }
  | {
      error: RuntimeJobError;
      job_id: string;
      type: "job_failed";
    }
  | {
      job_id: string;
      type: "job_cancelled";
    }
  | {
      event: AgentEventKind;
      job_id: string;
      type: "agent";
    }
  | {
      session_id: string;
      type: "session_started";
    }
  | {
      session_id: string;
      type: "turn_started";
    }
  | {
      session_id: string;
      type: "session_idle";
    }
  | {
      session_id: string;
      type: "session_closed";
    }
  | {
      event: AgentEventKind;
      session_id: string;
      type: "session_agent";
    }
  | {
      delta: string;
      index?: number | null;
      job_id: string;
      type: "tool_call_delta";
    }
  | {
      arguments: unknown;
      request_id: string;
      session_id: string;
      tool: string;
      type: "approval_requested";
    }
  | {
      kind: AuthEventKind;
      provider: string;
      type: "auth";
    };
/**
 * Payload of a [`RuntimeEvent::Agent`] — one step of the agent loop. Defined as transport-neutral data; the host maps its own agent events onto these.
 */
export type AgentEventKind =
  | {
      kind: "turn_started";
      turn: number;
    }
  | {
      kind: "message";
      text: string;
    }
  | {
      kind: "reasoning";
      text: string;
    }
  | {
      arguments: unknown;
      kind: "tool_started";
      tool: string;
    }
  | {
      kind: "tool_finished";
      ok: boolean;
      output: string;
      tool: string;
    }
  | {
      kind: "interrupted";
      reason: string;
    }
  | {
      /**
       * Prompt tokens written into the provider's prompt cache, when reported.
       */
      cache_creation_tokens?: number | null;
      /**
       * Prompt tokens served from the provider's prompt cache, when reported. Additive and optional: producers that don't track caching omit it.
       */
      cache_read_tokens?: number | null;
      input_tokens: number;
      kind: "usage";
      output_tokens: number;
    };
/**
 * Authentication lifecycle event kind. Defined as pure protocol data; hosts map concrete credential/login implementation details onto these states.
 */
export type AuthEventKind = "login_pending" | "login_completed" | "login_failed" | "credential_refreshed";
/**
 * Params payload of a `runtime/event` notification: the event itself plus a monotonic, per-stream sequence number so clients can detect dropped events and request replay. The event fields are flattened, so this is backward compatible with clients that read the bare event from `params`; `event_seq` is an additive sibling field (defaulting to 0 until a later wave assigns the real monotonic value at emit time).
 */
export type RuntimeEventNotification = {
  /**
   * Monotonically increasing, gap-detectable sequence number for this stream.
   */
  eventSeq?: number;
} & RuntimeEventNotification1;
export type RuntimeEventNotification1 =
  | {
      command: string;
      job_id: string;
      tool_name?: string | null;
      type: "job_started";
    }
  | {
      current?: number | null;
      job_id: string;
      message: string;
      stage: string;
      total?: number | null;
      type: "job_progress";
    }
  | {
      job_id: string;
      type: "job_cancel_requested";
    }
  | {
      job_id: string;
      type: "job_completed";
    }
  | {
      error: RuntimeJobError;
      job_id: string;
      type: "job_failed";
    }
  | {
      job_id: string;
      type: "job_cancelled";
    }
  | {
      event: AgentEventKind;
      job_id: string;
      type: "agent";
    }
  | {
      session_id: string;
      type: "session_started";
    }
  | {
      session_id: string;
      type: "turn_started";
    }
  | {
      session_id: string;
      type: "session_idle";
    }
  | {
      session_id: string;
      type: "session_closed";
    }
  | {
      event: AgentEventKind;
      session_id: string;
      type: "session_agent";
    }
  | {
      delta: string;
      index?: number | null;
      job_id: string;
      type: "tool_call_delta";
    }
  | {
      arguments: unknown;
      request_id: string;
      session_id: string;
      tool: string;
      type: "approval_requested";
    }
  | {
      kind: AuthEventKind;
      provider: string;
      type: "auth";
    };
/**
 * Status values used by daemon-owned runtime jobs.
 */
export type RuntimeJobStatus = "running" | "cancelling" | "completed" | "failed" | "cancelled";

export interface RuntimeProtocolSchema {
  jsonValue: unknown;
  runtimeCommand: RuntimeCommand;
  runtimeEvent: RuntimeEvent;
  runtimeEventNotification: RuntimeEventNotification;
  runtimeInfo: RuntimeInfo;
  runtimeJob: RuntimeJobSnapshot;
  runtimeJobCancelRequest: RuntimeJobCancelRequest;
  runtimeJobCancelResponse: RuntimeJobCancelResponse;
  runtimeJobError: RuntimeJobError;
  runtimeJobGetRequest: RuntimeJobGetRequest;
  runtimeJobListRequest: RuntimeJobListRequest;
  runtimeJobListResponse: RuntimeJobListResponse;
  runtimeJobResponse: RuntimeJobResponse;
  runtimeJobStartRequest: RuntimeJobStartRequest;
  runtimeToolSpec: RuntimeToolSpec;
  runtimeToolsListResponse: RuntimeToolsListResponse;
}
/**
 * Structured error stored on failed runtime jobs.
 */
export interface RuntimeJobError {
  kind: string;
  message: string;
}
export interface RuntimeInfo {
  capabilities: RuntimeCapabilities;
  protocol: string;
  protocolVersion: string;
  serverInfo: RuntimeServerInfo;
}
export interface RuntimeCapabilities {
  events: RuntimeEventCapabilities;
  jobs: RuntimeJobCapabilities;
  transport: RuntimeTransportCapabilities;
}
export interface RuntimeEventCapabilities {
  method: string;
}
export interface RuntimeJobCapabilities {
  commandKinds: string[];
  methods: string[];
}
export interface RuntimeTransportCapabilities {
  framing: string;
  jsonrpc: string;
}
export interface RuntimeServerInfo {
  name: string;
  version: string;
}
/**
 * Snapshot of a runtime job owned by a transport/daemon implementation.
 */
export interface RuntimeJobSnapshot {
  cancel_requested: boolean;
  command: string;
  created_at_ms: number;
  error?: RuntimeJobError | null;
  finished_at_ms?: number | null;
  job_id: string;
  result?: unknown;
  started_at_ms?: number | null;
  status: RuntimeJobStatus;
  tool_name?: string | null;
  updated_at_ms: number;
}
/**
 * Request payload for `runtime/jobs/cancel`.
 */
export interface RuntimeJobCancelRequest {
  job_id: string;
}
export interface RuntimeJobCancelResponse {
  cancellation_requested: boolean;
  job: RuntimeJobSnapshot;
}
/**
 * Request payload for `runtime/jobs/get`.
 */
export interface RuntimeJobGetRequest {
  include_result?: boolean;
  job_id: string;
}
/**
 * Request payload for `runtime/jobs/list`.
 */
export interface RuntimeJobListRequest {
  include_results?: boolean;
  include_terminal?: boolean;
  limit?: number;
}
export interface RuntimeJobListResponse {
  jobs: RuntimeJobSnapshot[];
}
export interface RuntimeJobResponse {
  job: RuntimeJobSnapshot;
}
/**
 * Request payload for `runtime/jobs/start`.
 */
export interface RuntimeJobStartRequest {
  command: RuntimeCommand;
  job_id?: string | null;
}
/**
 * Runtime-visible tool specification shape shared with frontend clients.
 */
export interface RuntimeToolSpec {
  description?: string | null;
  inputSchema?: unknown;
  name: string;
  [k: string]: unknown;
}
export interface RuntimeToolsListResponse {
  tools: RuntimeToolSpec[];
}
