// @generated by `bun run protocol:generate`
// Do not edit by hand. Rust protocol types in crates/ctx-runtime are the source of truth.

export const RUNTIME_DAEMON_NAME = "nerve" as const;
export const RUNTIME_EVENT_METHOD = "runtime/event" as const;
export const RUNTIME_INFO_METHOD = "runtime/info" as const;
export const RUNTIME_JOB_CANCEL_METHOD = "runtime/jobs/cancel" as const;
export const RUNTIME_JOB_GET_METHOD = "runtime/jobs/get" as const;
export const RUNTIME_JOB_LIST_METHOD = "runtime/jobs/list" as const;
export const RUNTIME_JOB_METHODS = ["runtime/jobs/start","runtime/jobs/get","runtime/jobs/list","runtime/jobs/cancel"] as const;
export const RUNTIME_JOB_START_METHOD = "runtime/jobs/start" as const;
export const RUNTIME_PROTOCOL_NAME = "nerve-runtime" as const;
export const RUNTIME_PROTOCOL_VERSION = "3" as const;
export const RUNTIME_TOOLS_LIST_METHOD = "runtime/tools/list" as const;

/**
 * Transport-neutral command understood by human-facing runtime adapters.
 */
export type RuntimeCommand =
  | {
      kind: "ping";
    }
  | {
      kind: "tool.list";
    }
  | {
      arguments?: {
        [k: string]: unknown;
      };
      kind: "tool.call";
      name: string;
    };
/**
 * Runtime event emitted by human-facing adapters while executing jobs.
 */
export type RuntimeEvent =
  | {
      command: string;
      job_id: string;
      tool_name?: string | null;
      type: "job_started";
    }
  | {
      current?: number | null;
      job_id: string;
      message: string;
      stage: string;
      total?: number | null;
      type: "job_progress";
    }
  | {
      job_id: string;
      type: "job_cancel_requested";
    }
  | {
      job_id: string;
      type: "job_completed";
    }
  | {
      error: RuntimeJobError;
      job_id: string;
      type: "job_failed";
    }
  | {
      job_id: string;
      type: "job_cancelled";
    };
/**
 * Status values used by daemon-owned runtime jobs.
 */
export type RuntimeJobStatus = "running" | "cancelling" | "completed" | "failed" | "cancelled";

export interface RuntimeProtocolSchema {
  jsonValue: unknown;
  runtimeCommand: RuntimeCommand;
  runtimeEvent: RuntimeEvent;
  runtimeInfo: RuntimeInfo;
  runtimeJob: RuntimeJobSnapshot;
  runtimeJobCancelRequest: RuntimeJobCancelRequest;
  runtimeJobCancelResponse: RuntimeJobCancelResponse;
  runtimeJobError: RuntimeJobError;
  runtimeJobGetRequest: RuntimeJobGetRequest;
  runtimeJobListRequest: RuntimeJobListRequest;
  runtimeJobListResponse: RuntimeJobListResponse;
  runtimeJobResponse: RuntimeJobResponse;
  runtimeJobStartRequest: RuntimeJobStartRequest;
  runtimeToolSpec: RuntimeToolSpec;
  runtimeToolsListResponse: RuntimeToolsListResponse;
}
/**
 * Structured error stored on failed runtime jobs.
 */
export interface RuntimeJobError {
  kind: string;
  message: string;
}
export interface RuntimeInfo {
  capabilities: RuntimeCapabilities;
  protocol: string;
  protocolVersion: string;
  serverInfo: RuntimeServerInfo;
}
export interface RuntimeCapabilities {
  events: RuntimeEventCapabilities;
  jobs: RuntimeJobCapabilities;
  transport: RuntimeTransportCapabilities;
}
export interface RuntimeEventCapabilities {
  method: string;
}
export interface RuntimeJobCapabilities {
  commandKinds: string[];
  methods: string[];
}
export interface RuntimeTransportCapabilities {
  framing: string;
  jsonrpc: string;
}
export interface RuntimeServerInfo {
  name: string;
  version: string;
}
/**
 * Snapshot of a runtime job owned by a transport/daemon implementation.
 */
export interface RuntimeJobSnapshot {
  cancel_requested: boolean;
  command: string;
  created_at_ms: number;
  error?: RuntimeJobError | null;
  finished_at_ms?: number | null;
  job_id: string;
  result?: unknown;
  started_at_ms?: number | null;
  status: RuntimeJobStatus;
  tool_name?: string | null;
  updated_at_ms: number;
}
/**
 * Request payload for `runtime/jobs/cancel`.
 */
export interface RuntimeJobCancelRequest {
  job_id: string;
}
export interface RuntimeJobCancelResponse {
  cancellation_requested: boolean;
  job: RuntimeJobSnapshot;
}
/**
 * Request payload for `runtime/jobs/get`.
 */
export interface RuntimeJobGetRequest {
  include_result?: boolean;
  job_id: string;
}
/**
 * Request payload for `runtime/jobs/list`.
 */
export interface RuntimeJobListRequest {
  include_results?: boolean;
  include_terminal?: boolean;
  limit?: number;
}
export interface RuntimeJobListResponse {
  jobs: RuntimeJobSnapshot[];
}
export interface RuntimeJobResponse {
  job: RuntimeJobSnapshot;
}
/**
 * Request payload for `runtime/jobs/start`.
 */
export interface RuntimeJobStartRequest {
  command: RuntimeCommand;
  job_id?: string | null;
}
/**
 * Runtime-visible tool specification shape shared with frontend clients.
 */
export interface RuntimeToolSpec {
  description?: string | null;
  inputSchema?: unknown;
  name: string;
  [k: string]: unknown;
}
export interface RuntimeToolsListResponse {
  tools: RuntimeToolSpec[];
}
