import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { compileFromFile } from "json-schema-to-typescript";

const SCHEMA_PATH = "docs/protocol/runtime-v3.schema.json";
const CONSTANTS_PATH = "docs/protocol/runtime-v3.constants.json";
const TYPESCRIPT_PATH = "packages/tui/src/backend/protocol.generated.ts";

const check = process.argv.slice(2).includes("--check");
const root = findRepoRoot();
const outputPath = resolve(root, TYPESCRIPT_PATH);
const expected = await generatedTypescript(root);

if (check) {
  const actual = existsSync(outputPath) ? readFileSync(outputPath, "utf8") : "";
  if (actual !== expected) {
    throw new Error(`runtime protocol TypeScript is stale: ${TYPESCRIPT_PATH}. Run \`bun run protocol:generate\`.`);
  }
} else {
  writeFileSync(outputPath, expected);
}

async function generatedTypescript(rootDir: string): Promise<string> {
  const constants = JSON.parse(readFileSync(resolve(rootDir, CONSTANTS_PATH), "utf8")) as Record<string, unknown>;
  const types = await compileFromFile(resolve(rootDir, SCHEMA_PATH), {
    additionalProperties: false,
    bannerComment: "",
  });
  return `${generatedHeader()}${renderConstants(constants)}${types.trimStart()}`;
}

function generatedHeader(): string {
  return "// @generated by `bun run protocol:generate`\n" +
    "// Do not edit by hand. Rust protocol types in crates/ctx-runtime are the source of truth.\n\n";
}

function renderConstants(constants: Record<string, unknown>): string {
  return Object.entries(constants)
    .map(([name, value]) => `export const ${name} = ${JSON.stringify(value)} as const;`)
    .join("\n") + "\n\n";
}

function findRepoRoot(): string {
  for (let dir = process.cwd(); ; dir = dirname(dir)) {
    if (existsSync(resolve(dir, "Cargo.toml")) && existsSync(resolve(dir, "packages/tui"))) return dir;
    const parent = dirname(dir);
    if (parent === dir) throw new Error(`failed to locate repository root from ${process.cwd()}`);
  }
}
